config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/users/:id', to: 'profiles#show', as: "profile"

  resources :gardens, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:new, :create] 
  end
  resources :bookings, only: [:show] do
    member do
      put :accept
      put :decline
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :garden
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true

  # validates :status, inclusion: { in: %w(pending accepted declined) }

  validate :end_date_after_start_date?
    def end_date_after_start_date?
      if end_date < start_date
        errors.add :end_date, "must be after start date"
      end
    end

  def add_booked_days_to_garden
    self.garden.booked << { from: self.start_date, to: self.end_date }
  end

  def total_price
    days = ((self.end_date - self.start_date) + 1).to_i
    self.garden.price_per_day * days
  end
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many_attached :photos
  belongs_to :user 
  has_many :bookings, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 50 }
  validates :address, presence: true
  validates :price_per_day, presence: true

  serialize :booked,Array

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_address,
    against: [ :address],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/garden_review.rb
class GardenReview < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :bookings, dependent: :destroy
  has_many :gardens, dependent: :destroy

  has_one :profile, dependent: :destroy
  after_create :init_profile

  def init_profile
    self.create_profile!
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_booking, only: [:show, :accept, :decline]

  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def new
    @garden = Garden.find(params[:garden_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(bookings_params)
    @garden = Garden.find(params[:garden_id])
    @booking.garden = @garden
    @booking.user = current_user
    authorize @booking
    if @booking.save
      if @garden.user == current_user
        @booking.update_column(:status, "accepted")
        add_booked_days_to_garden(@booking)
        redirect_to profile_path(current_user)
      else
        redirect_to booking_path(@booking)
      end
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @qr_code = RQRCode::QRCode.new("www.lewagon.com")
    @svg = @qr_code.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      standalone: true
    )
    authorize @booking
  end

  def update
  end

  def accept
    @booking.update_column(:status, "accepted")
    add_booked_days_to_garden(@booking)
    authorize @booking
    redirect_to profile_path(current_user, anchor: "booking-#{@booking.id}")
  end

  def decline
    @booking.update_column(:status, "declined")
    authorize @booking
    redirect_to profile_path(current_user, anchor: "booking-#{@booking.id}")
  end

  private

  def bookings_params
    params.require(:booking).permit(:user_introduction, :start_date, :end_date, :qr_code)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def add_booked_days_to_garden(booking)
    booked = booking.garden.booked
    booked << { from: booking.start_date, to: booking.end_date }
    booking.garden.update_column(:booked, booked)
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @gardens = policy_scope(Garden).search_by_address(params[:query])
    else
      @gardens = policy_scope(Garden).order(created_at: :desc)
    end
    # geolocation markers
    @markers = @gardens.geocoded.map do |garden|
      {
        lat: garden.latitude,
        lng: garden.longitude,
        info_window: render_to_string(partial: "info_window", locals: { garden: garden })
      }
    end
  end

  def new
    @garden = Garden.new
    authorize @garden
  end

  def create
    @garden = Garden.new(garden_params)
    @garden.user = current_user
    authorize @garden
    if @garden.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def show
    @garden = Garden.find(params[:id])
    authorize @garden
  end

  private

  def garden_params
    params.require(:garden).permit(:name, :description, :address, :price_per_day, photos: [])
  end   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = current_user.profile
    authorize @profile
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= render 'shared/navbar'%>
<% if current_user == @garden.user %>
  <h1 style="margin: 0 auto;">Block days for my stay in my garden</h1>
  <div class="container">
    <div class="form-wrapper"
      style="width:350px; margin: 0 auto;"
      id="booking_form"
      data-booked="<%= @garden.booked.to_json %>">
      <%= simple_form_for [@garden, @booking] do |f| %>
        <%= f.input :start_date, as: :string, required: false, input_html: { id: "range_start" } %>
        <%= f.input :end_date, as: :string, required: false, input_html: { id: "range_end" } %>
        <%= f.submit "Block days", class: "btn btn-layout btn-book" %>
      <% end %>
    </div>
  </div>
<% else %>
  <h1 style="margin: 0 auto;">New booking</h1>
  <div class="container">
    <div class="form-wrapper"
      style="width:350px; margin: 0 auto;"
      id="booking_form"
      data-booked="<%= @garden.booked.to_json %>">
      <%= simple_form_for [@garden, @booking] do |f| %>
        <%= f.input :start_date, as: :string, required: false, input_html: { id: "range_start" } %>
        <%= f.input :end_date, as: :string, required: false, input_html: { id: "range_end" } %>
        <%= f.input :user_introduction, label: "Leave a message to the host", placeholder: "Write your message..." %>
        <%= f.submit "Book your garden", class: "btn btn-layout btn-book" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/bookings/show.html.erb
<%= render 'shared/navbar'%>

<div class="confirmation-page text-center">
  <div class="confirmation-page-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('garden.jpg') %>);">
    <div class="container">
      <h1>Thank you for you booking!</h1>
      <p>Your request has been sent to the host!
      <br>
        Please wait for the confirmation.
      </p>
      <%= link_to "Check request status", profile_path(@booking), {:class => "btn btn-success btn-layout btn-custom"}%>  
    </div>
  </div>

<div class="container text-center">
  <div class="row">
    <div class="col-sm">
      <img src="https://source.unsplash.com/random/220x220/?garden">
    </div>

    <div class="col-sm pt-4">
      <div>You will be staying at:</div>
      <div class="p-2 font-weight-bold"><%= @booking.garden.name.upcase %> </div>
      <div class="p-2">Address: <%= @booking.garden.address %></div>
      <div>From: <%= @booking.start_date.strftime("%B %e, %Y") %> </div>
      <div>To: <%= @booking.end_date.strftime("%B %e, %Y") %></div>
      <div class="p-2 font-weight-bold">Total Price: <%= @booking.total_price %>€</div>
    </div>
  </div>
</div>

app/views/gardens/_info_window.html.erb
<h4><%= garden.name %></h4>
<p><%= garden.address %></p>

app/views/gardens/index.html.erb
<%= render 'shared/navbar'%>

<% hosts = ["zuzanasoltisova", "federico-dev", "aphanite"] %>
<div class="main-container">
  <div class="garden-info">
    <div class="garden-header d-flex justify-content-between">
      <% if params[:query] %>
        <h2> Gardens in <%= params[:query].capitalize %></h2>
      <% else %>
        <h2> Gardens in Berlin</h2>
      <% end %>
      <p> <%= @gardens.count %> objects </p>
    </div>

    <div class="container-gardens">

      <% @gardens.each do |garden| %>

        <%= link_to garden_path(garden), {:style=>'color:#000000; text-decoration : none'}  do %>
          <div class="card-trip">
            <img src="https://source.unsplash.com/random/1180×240/?garden" />
            <div class="card-trip-infos">
              <div>
                <h2><%= garden.name %></h2>
                <p><%= garden.address %></p>
              </div>
              <h2 class="card-trip-pricing"><%= garden.price_per_day %>€</h2>
              <img src="https://kitt.lewagon.com/placeholder/users/<%= hosts.sample %>" class="card-trip-user avatar-bordered" />
            </div>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>

  <div class="container-map">
    <div id="map"
      style="width: 100%; height: 850px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

</div>

app/views/gardens/show.html.erb
<%= render 'shared/navbar'%>

<!-- Garden Images-->
<div class="container-garden">
 <h2><%= @garden.name %> by <%= @garden.user.name %></h2>
    <% if @garden.photos.attached? %>
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= cl_image_tag @garden.photos[0], :class=> "d-block w-100" %>
    </div>
    <div class="carousel-item">
      <%= cl_image_tag @garden.photos[1], :class=> "d-block w-100" %>
    </div>
    <!-- <div class="carousel-item">
      <img class="d-block w-100" src="https://source.unsplash.com/featured/?garden" alt="Third slide">
    </div> -->
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
    <% else %>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://source.unsplash.com/featured/?garden" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://source.unsplash.com/featured/?garden" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://source.unsplash.com/featured/?garden" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
   <% end %>

 <!-- Garden Location and Price -->
 <div class="garden-content">
  <div class="garden-description">
    <p><%= @garden.description%></p>
  </div>

  <div class="garden-info-flex">
      <p><%= @garden.address %></p>
      <p><strong>Price Per Day:</strong> €<%= @garden.price_per_day %></p>
      <% if current_user === @garden.user %>
      <%= link_to "Block dates for me",new_garden_booking_path(@garden), {:class => "btn btn-layout btn-block "} %>
      <% else %>
      <%= link_to "Book now", new_garden_booking_path(@garden), {:class => "btn btn-layout btn-book"}%>
      <% end %>
    </div>
</div>
</div>

app/views/pages/home.html.erb
<!-- Banner -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('garden.jpg') %>);">
  <!-- Navbar -->
  <div class="navbar navbar-expand-sm  navbar-fixed-top navbar-lewagon">
    <a class="navbar-brand" href="/">
      <%= image_tag('logo-gardenBnB-normal.png') %>
    </a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
           <%= link_to "Offer your garden", new_garden_path, class: "nav-link"%>
          </li>
          <li class="nav-item active">
             <%= link_to "Profile", profile_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, class: "nav-link", method: :delete, data: { confirm: "Are you sure?" } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Offer your garden", new_garden_path, class: "nav-link"%>
          </li>
          <li class="nav-item active">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>


  <!-- Banner content -->
  <div class="container">
    <h1>Dreaming of your own garden?</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

    <%= form_tag gardens_path, method: :get do %>
      <div class="search-form-control form-group">
        <div class="form-control">
            <%= text_field_tag :query, params[:query], placeholder: "Where should your garden be?" %>
          <button name="button" type="submit" class="btn btn-custom">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- Discover gardens by location  -->
<div class="card-discover">
  <h3>Discover gardens nearby</h3>
</div>

<!-- City cards  -->
<div class="row">
  <div class="card-city">
  <img src="https://images.unsplash.com/photo-1563127673-00fb29e7eeae?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="">
    <div class="card-city-infos">
      <h2>Berlin</h2>
      <%= link_to "", gardens_path, class: "stretched-link" %>
    </div>
  </div>
  <div class="card-city">
  <img src="https://images.unsplash.com/photo-1444392061186-9fc38f84f726?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1352&q=80" alt="">
    <div class="card-city-infos">
      <h2>Munich</h2>
      <%= link_to "", gardens_path, class: "stretched-link" %>
    </div>
  </div>
  <div class="card-city">
  <img src="https://images.unsplash.com/photo-1576897955702-24ad19680db3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80" alt="">
    <div class="card-city-infos">
      <h2>Hamburg</h2>
      <%= link_to "", gardens_path, class: "stretched-link" %>
    </div>
  </div>
  <div class="card-city">
  <img src="https://images.unsplash.com/photo-1612143398944-0fc4e9671f96?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80" alt="">
    <div class="card-city-infos">
      <h2>Frankfurt</h2>
      <%= link_to "", gardens_path, class: "stretched-link" %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<%= render 'shared/navbar'%>
<div class="container" style="padding: 50px 15px;">
  <div class="main-body">

    <div class="row gutters-sm">
      <div class="col-md-4 mb-3">
        <div class="card" id="profile-summary">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
              <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
              <div class="mt-3">
                <h4><%= current_user.name %></h4>
                <p class="text-secondary mb-1"><%= ["Happy gardener", "Outdoor fanatic", "Garden freak", "Nature lover"].sample %></p>
                <p class="text-muted font-size-sm">Berlin</p>
                <hr>
                <p class="text-secondary mb-1"> <i class="fas fa-comment" style="color: #f9c784;"></i> 0 reviews</p>
                <p class="text-secondary mb-1"> <i class="fas fa-certificate" style="color: #45cb85;"></i> Identity verified</p>
                <hr>
                <a class="btn btn-edit btn-layout" target="__blank" href="#">Edit</a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- User Bookings -->
      <% user_bookings = Booking.where(user: current_user) %>
      <% user_gardens = current_user.gardens %>

      <div class="col-md-8">
        <% unless user_bookings.empty? %>
          <div class="card mb-3">
            <div class="card-body">

              <div class="row">
                <div class="col-sm-12 d-flex justify-content-between">
                  <h3 class="mb-0" style="padding-left: 8px;">My bookings (<%= user_bookings.reject{ |b| b.garden.user.name == b.user.name }.count %>)</h3>
                  <h3 class="mb-0" style="padding-right: 16px;"><i class="far fa-calendar-alt"></i></h3>
                </div>
              </div>

              <% user_bookings.each do |b| %>
                <% unless b.garden.user == current_user %>
                  <div class="garden" style="margin: 12px 0; background-color: #f5f5f5; padding: 8px 12px;">
                    <div class="row pt-3">
                      <div class="col-sm-3">
                        <h6 class="mb-0"><strong>Garden</strong> </h6>
                      </div>
                      <div class="col-sm-9 text-secondary">
                        <%= b.garden.name %> by <%= b.garden.user.name %>
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0">Address</h6>
                      </div>
                      <div class="col-sm-9 text-secondary">
                        <%= b.garden.address %>
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0">Dates</h6>
                      </div>
                      <div class="col-sm-9 text-secondary">
                        From <%= b.start_date.strftime("%B %e, %Y") %> to <%= b.end_date.strftime("%B %e, %Y") %>
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0">Status</h6>
                      </div>
                      <div class="col-sm-9 text-secondary">
                        <% if b.status == "accepted"%>
                          <p style="margin-bottom: 0;"><i class="far fa-check-circle" style="color:#1EDD88; margin-right: 4px;"></i> <%= b.garden.user.name %> accepted your request</p>
                        <% elsif b.status == "declined"%>
                          <p style="margin-bottom: 0;"><i class="far fa-times-circle" style="color:red; margin-right: 4px;"></i> <%= b.garden.user.name %> declined your request</p>
                        <% else %>
                          <p style="margin-bottom: 0;"><i class="far fa-clock" style="color:grey; margin-right: 4px;"></i> <%= b.garden.user.name %> will soon reply</p>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>

      <!-- User gardens -->
        <% unless user_gardens.empty? %>

        <div class="card mb-3">
          <div class="card-body">
            <div class="row">

              <div class="col-sm-12 d-flex justify-content-between">
                <h3 class="mb-0" style="padding-left: 8px;">My gardens (<%= user_gardens.count %>)</h3>
                <h3 class="mb-0" style="padding-right: 16px; color:#153131;"><i class="fab fa-pagelines"></i></h3>
              </div>
            </div>
            <% user_gardens.each do |g| %>
              <div class="garden" style="margin: 12px 0; background-color: #f5f5f5; padding: 8px 12px;">
                <div class="row pt-3">
                  <div class="col-sm-3">
                    <h6 class="mb-0"><strong>Garden</strong> </h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    <%= g.name %>
                  </div>
                </div>

                <hr>

                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">Address</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    <%= g.address %>
                  </div>
                </div>

                <hr>

                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">Blocked days</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">

                    <% owner_bookings = user_bookings.select{ |b| b.garden.user.name == b.user.name && b.garden == g}%>

                    <% if owner_bookings.empty? %>
                      No blocked days
                    <% else %>

                        <% owner_bookings.each do |ob|%>
                         From <%= ob.start_date.strftime("%B %e, %Y") %> to <%= ob.end_date.strftime("%B %e, %Y") %><br>
                        <% end %>

                    <% end %>

                  </div>
                </div>

                <hr>

                <% unless g.bookings.empty? %>

                  <div class="row">
                    <div class="col-sm-9">
                      <h6><i class="far fa-calendar-alt"></i> <strong>Bookings for this garden</strong></h6>
                    </div>
                  </div>



                  <% g.bookings.each do |book| %>
                    <% unless book.user == current_user %>
                      <div class="card-body" style="background-color: #ededed; margin: 12px 0;">
                        <div class="row" id="booking-<%= book.id %>">
                          <div class="col-sm-3">
                            <h6 class="mb-0">Guest</h6>
                          </div>
                          <div class="col-sm-9 text-secondary">
                            <%= book.user.name %>
                          </div>
                        </div>
                        <hr>

                        <div class="row">
                          <div class="col-sm-3">
                            <h6 class="mb-0">Dates</h6>
                          </div>
                          <div class="col-sm-9 text-secondary">
                            From <%= book.start_date.strftime("%B %e, %Y") %> to <%= book.end_date.strftime("%B %e, %Y") %>
                          </div>
                        </div>
                        <hr>

                        <div class="row">
                          <div class="col-sm-3">
                            <h6 class="mb-0">Status</h6>
                          </div>
                          <div class="col-sm-9 text-secondary">
                            <% if book.status == "accepted"%>
                              <p style="margin-bottom: 0;"><i class="far fa-check-circle" style="color:#1EDD88; margin-right: 4px;"></i> You accepted <%= book.user.name%>'s request</p>
                            <% elsif book.status == "declined"%>
                              <p style="margin-bottom: 0;"><i class="far fa-times-circle" style="color:red; margin-right: 4px;"></i> You declined <%= book.user.name%>'s request</p>
                            <% else %>
                              <p style="margin-bottom: 0;"><i class="far fa-clock" style="color:grey; margin-right: 4px;"></i>  Please reply to <%= book.user.name  %> soon!</p>
                            <% end %>
                          </div>
                        </div>
                        <% if book.status == "pending" %>
                          <hr>
                          <div class="row">
                            <div class="col-sm-12 d-flex justify-content-center">
                              <%= link_to "Accept",accept_booking_path(book), :method=>"PUT",  class: "btn btn-accept btn-layout", remote: true%>
                              <%= link_to "Decline",decline_booking_path(book), :method=>"PUT",  class: "btn btn-decline btn-layout", remote: true%>
                            </div>
                          </div>
                      <% end %>
                      </div>
                    <% end %>
                  <% end %>

                <% end %>

                <div class="row">
                  <div class="col-sm-12 d-flex justify-content-center">
                    <a class="btn btn-edit btn-layout" target="__blank" href="https://www.bootdey.com/snippets/view/profile-edit-data-and-skills">Edit</a>
                    <%= link_to "Block days for me", new_garden_booking_path(g), class: "btn-block-days"%>
                  </div>
                </div>

              </div>
            <% end %>
          </div>
         </div>
        <% end %>
      </div>
    </div>
  </div>
</div>